#!/bin/bash
#SBATCH --job-name="init_P3HT_Solvent_50_300"
#SBATCH --output="lammpsgpu.%j.%N.out"
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --no-requeue
#SBATCH --gres=gpu:4
#SBATCH -t 048:00:00
#SBATCH -A csd467
cd /oasis/scratch/comet/seroot/temp_project/CGMD/P3HT_Solvent_50_300

module unload mvapich2_ib
module unload intel
module load intel/2015.2.164
module load mvapich2_ib
module load cuda

ibrun -np 8 /share/apps/gpu/lammps/lmp_cuda_mpi -sf gpu -pk gpu 4 -in in.init_P3HT_Solvent_50_300 -log log.init_P3HT_Solvent_50_300
